# Generated by Django 5.1.6 on 2025-02-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(default='2000-01-01', max_length=50, unique=True)),
                ('vulnerability_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=50)),
                ('published_date', models.DateField()),
                ('source_url', models.URLField()),
            ],
        ),
    ]
