# Generated by Django 5.1.6 on 2025-03-01 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntelligenceArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('source', models.CharField(max_length=100)),
                ('url', models.URLField(unique=True)),
                ('published_date', models.DateTimeField()),
                ('summary', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-published_date'],
                'indexes': [models.Index(fields=['source'], name='ioc_scraper_source_0b16a6_idx'), models.Index(fields=['published_date'], name='ioc_scraper_publish_6d0af5_idx')],
            },
        ),
    ]
