# Generated by Django 5.1.6 on 2025-03-01 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0002_intelligencearticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdStrikeIntel',
            fields=[
                ('actor_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('capabilities', models.JSONField(blank=True, null=True)),
                ('motivations', models.JSONField(blank=True, null=True)),
                ('objectives', models.JSONField(blank=True, null=True)),
                ('adversary_type', models.CharField(blank=True, max_length=100, null=True)),
                ('origins', models.JSONField(blank=True, null=True)),
                ('last_update_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
