# Generated by Django 5.1.6 on 2025-03-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0004_crowdstrikemalware'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdStrikeTailoredIntel',
            fields=[
                ('id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('threat_groups', models.JSONField(blank=True, default=list)),
                ('nation_affiliations', models.JSONField(blank=True, default=list)),
                ('targeted_sectors', models.JSONField(blank=True, default=list)),
                ('targeted_countries', models.JSONField(blank=True, default=list)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'CrowdStrike Tailored Intel',
                'verbose_name_plural': 'CrowdStrike Tailored Intel',
            },
        ),
    ]
