# Generated by Django 5.1.6 on 2025-03-02 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0005_crowdstriketailoredintel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CISAKev',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=50, unique=True)),
                ('vulnerability_name', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('date_added', models.DateField()),
                ('due_date', models.DateField()),
                ('vendor_project', models.CharField(max_length=255)),
                ('product', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CISA Known Exploited Vulnerability',
                'verbose_name_plural': 'CISA Known Exploited Vulnerabilities',
                'ordering': ['-date_added'],
            },
        ),
        migrations.DeleteModel(
            name='CrowdStrikeTailoredIntel',
        ),
    ]
