# Generated by Django 5.1.6 on 2025-03-09 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0006_cisakev_delete_crowdstriketailoredintel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdStrikeTailoredIntel',
            fields=[
                ('report_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('publish_date', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('report_url', models.URLField(blank=True, max_length=500, null=True)),
                ('threat_groups', models.TextField(blank=True, null=True)),
                ('targeted_sectors', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CrowdStrike Tailored Intel',
                'verbose_name_plural': 'CrowdStrike Tailored Intel',
            },
        ),
    ]
