# Generated by Django 5.1.6 on 2025-03-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0007_crowdstriketailoredintel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowdstriketailoredintel',
            name='targeted_sectors',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstriketailoredintel',
            name='threat_groups',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddIndex(
            model_name='crowdstriketailoredintel',
            index=models.Index(fields=['publish_date'], name='ioc_scraper_publish_2eff78_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdstriketailoredintel',
            index=models.Index(fields=['last_updated'], name='ioc_scraper_last_up_1ea1f3_idx'),
        ),
        migrations.AddIndex(
            model_name='crowdstriketailoredintel',
            index=models.Index(fields=['title'], name='ioc_scraper_title_a2dcd8_idx'),
        ),
    ]
