# Generated by Django 5.1.6 on 2025-03-10 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0008_alter_crowdstriketailoredintel_targeted_sectors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crowdstriketailoredintel',
            name='targeted_sectors_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name='crowdstriketailoredintel',
            name='threat_groups_json',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstriketailoredintel',
            name='targeted_sectors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='crowdstriketailoredintel',
            name='threat_groups',
            field=models.TextField(blank=True, null=True),
        ),
    ]
