# Generated by Django 5.1.6 on 2025-03-10 23:20

from django.db import migrations

def convert_text_to_json(apps, schema_editor):
    """
    Convert comma-separated text fields to JSON array fields
    """
    # Get the historical model
    CrowdStrikeTailoredIntel = apps.get_model('ioc_scraper', 'CrowdStrikeTailoredIntel')
    
    # Process all existing records
    for intel in CrowdStrikeTailoredIntel.objects.all():
        # Convert threat_groups text to JSON
        if intel.threat_groups and not intel.threat_groups_json:
            intel.threat_groups_json = [group.strip() for group in intel.threat_groups.split(',') if group.strip()]
        
        # Convert targeted_sectors text to JSON
        if intel.targeted_sectors and not intel.targeted_sectors_json:
            intel.targeted_sectors_json = [sector.strip() for sector in intel.targeted_sectors.split(',') if sector.strip()]
        
        # Save the changes
        intel.save()

def revert_json_to_text(apps, schema_editor):
    """
    Revert JSON data back to text fields (for rollback)
    """
    # Get the historical model
    CrowdStrikeTailoredIntel = apps.get_model('ioc_scraper', 'CrowdStrikeTailoredIntel')
    
    # Process all existing records
    for intel in CrowdStrikeTailoredIntel.objects.all():
        # Convert JSON arrays back to text if needed
        if intel.threat_groups_json and not intel.threat_groups:
            intel.threat_groups = ', '.join(intel.threat_groups_json)
        
        if intel.targeted_sectors_json and not intel.targeted_sectors:
            intel.targeted_sectors = ', '.join(intel.targeted_sectors_json)
        
        # Save the changes
        intel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0009_crowdstriketailoredintel_targeted_sectors_json_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_text_to_json, revert_json_to_text),
    ]
