# Generated by Django 5.1.6 on 2025-03-10 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ioc_scraper', '0010_auto_20250310_1920'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cisakev',
            index=models.Index(fields=['cve_id'], name='ioc_scraper_cve_id_40d6de_idx'),
        ),
        migrations.AddIndex(
            model_name='cisakev',
            index=models.Index(fields=['date_added'], name='ioc_scraper_date_ad_ae0d72_idx'),
        ),
        migrations.AddIndex(
            model_name='cisakev',
            index=models.Index(fields=['vendor_project'], name='ioc_scraper_vendor__b4d645_idx'),
        ),
        migrations.AddIndex(
            model_name='cisakev',
            index=models.Index(fields=['product'], name='ioc_scraper_product_c8d388_idx'),
        ),
    ]
